<?php
/**
 * Created by PhpStorm.
 * Date: 2019/3/12
 * Time: 16:46
 */

class ArrayHook extends ArrayObject {
    private $UseList;

    /**
     * @return mixed
     */
    public function getUseList()
    {
        return $this->UseList;
    }

    /**
     * @param mixed $UseList
     */
    public function setUseList($UseList)
    {
        $this->UseList = $UseList;
    }


    public function __construct($input = array(), $flags = 0, $iterator_class = "ArrayIterator", $init = array())
    {
        parent::__construct($input, $flags, $iterator_class);
        self::setUseList($init);
    }

    public function offsetGet($index)
    {
        $tmp = $this->getUseList();
        $tmp[$index] = 1;
        $this->setUseList($tmp);
        parent::offsetGet($index); // TODO: Change the autogenerated stub
    }

    public function __call($func, $argv)
    {
        if (!is_callable($func) || substr($func, 0, 6) !== 'array_')
        {
            throw new BadMethodCallException(__CLASS__.'->'.$func);
        }
        return call_user_func_array($func, array_merge(array($this->getArrayCopy()), $argv));
    }

}